### ISSUE TITLE
version 5.0.1 cant find type declarations

### ISSUE THREAD

**Issue by thomasbrettell** [abcnews/env-utils#33]
`import { whenOdysseyLoaded } from '@abcnews/env-utils';`
Cannot find module '@abcnews/env-utils' or its corresponding type declarations.ts(2307)

Works fine in version 4.0.0

**Comment by AshKyd** [comment]
Fixed in 15e16e6b434e5b94c20c016fbdc443e379eaa502
